name: Generate Terraform Docs

on:
  push:
    branches: [ "master" ]
  pull_request:

jobs:
  docs:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Generate README with terraform-docs
        uses: terraform-docs/gh-actions@v1.0.0
        with:
          working-dir: .
          output-file: README.md
          output-method: inject
          git-push: true
